[changelog]
header = "# Changelog\n"
body = """
## {{ version }}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
* {{ commit.message }}
{% endfor %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^doc", group = "Documentation" },
  { message = "^perf", group = "Improvements" },
  { message = "^improve", group = "Improvements" },
  { message = "^chore", skip = true },
]
